[phases.setup]
aptPkgs = [
  "unzip",
  "poppler-utils",
  "libreoffice",
  "tesseract-ocr",
  "tesseract-ocr-spa",
  "tesseract-ocr-eng"
]

[phases.build]
cmds = ["npm run build", "cp -r DocPlant dist/DocPlant"]

[start]
cmd = "node dist/server.js"
