[phases.setup]
aptPkgs = [
  "unzip",
  "poppler-utils",
  "tesseract-ocr",
  "tesseract-ocr-spa",
  "tesseract-ocr-eng",
  "libreoffice",
  "fonts-liberation",
  "fonts-dejavu-core",
  "fontconfig"
]
